version: '3.7'

services:
  postgres:
    image: postgres:11.1
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./log:/root/log
    ports:
      - 5432:5432

  rails:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: dock_app:1.0.1
    tmpfs:
      - /tmp
    stdin_open: true
    tty: true
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - 3000:3000
    volumes:
      - packs:/app/public/packs
      - node_modules:/app/node_modules
      - rails_cache:/app/tmp/cache
      - bundle:/bundle
      - .:/app:cached
    environment:
      - NODE_ENV=development
      - RAILS_ENV=${RAILS_ENV:-development}
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/dock_app_development?pool=5
      - BOOTSNAP_CACHE_DIR=/bundle/bootsnap
      - WEBPACKER_DEV_SERVER_HOST=webpacker
      - WEB_CONCURENCY=1
      - HISTFILE=/app/log/.bash_history
      - PSQL_HISTFILE=/app/log/.psql_history
      - EDITOR=vi
    depends_on:
      - postgres

        # webpacker:
        #   build:
        #     context: .
        #     dockerfile: ./Dockerfile
        #   image: dock_app:1.0
        #   tmpfs:
        #     - /tmp
        #   stdin_open: true
        #   tty: true
        #   command: bin/webpack-dev-server
        #   ports:
        #     - 3035:3035
        #   volumes:
        #     - .:/app:cached
        #     - bundle:/bundle
        #     - node_modules:/app/node_modules
        #     - packs:/app/public/packs
        #   environment:
        #     - NODE_ENV=${NODE_ENV:-development}
        #     - RAILS_ENV=${RAILS_ENV:-development}
        #     - WEBPACKER_DEV_SERVER_HOST=0.0.0.0


volumes:
  postgres:
  rails_cache:
  node_modules:
  bundle:
  packs:
